apiVersion: v1
kind: Pod
metadata:
  name: secret-example
spec:
    containers:
      - name: secret-example
        image: alpine:latest
        command: ["sleep", "9999"]
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: simple-secret
                key: username
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: simple-secret
                key: password
